document.write("    <header class='navbar'>"),
document.write('        <div class="logo_space">'),
document.write('            <div class="logo_area">'),
document.write('                <a href="https://astreait.com/" class="logo" title="ASTREA IT">'),
document.write('                    <img src="https://astreait.com/images/ASTREAITLogo.png">'),
document.write("                </a>"),
document.write("            </div>"),
document.write("        </div>"),
document.write('        <div class="menu_list">'),
document.write('            <nav class="main-nav" role="navigation">'),
document.write("                \x3c!-- Mobile menu toggle button (hamburger/x icon) --\x3e"),
document.write('                <input id="main-menu-state" type="checkbox" />'),
document.write(""),
document.write('                <label class="main-menu-btn" for="main-menu-state">'),
document.write('                    <span class="main-menu-btn-icon"></span> menu'),
document.write("                </label>"),
document.write(""),
document.write('                <ul id="main-menu" class="sm sm-blue">'),
document.write('                    <li><a href="https://astreait.com/">Home</a></li>'),
document.write(""),
document.write("                    \x3c!-- has sub child  started --\x3e"),
document.write('                    <li class="has_particular"><a class="particular_toggle1" href="https://astreait.com/services/">Services</a>'),
document.write('                        <a class="particular_toggle2  col-11" href="https://astreait.com/services/">Services</a>'),
document.write('                        <a class="col-1" href="javascript:void()"> <img class="services_toggle" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write(""),
document.write('                        <ul class="submenus">'),
document.write('                            <li><a href="https://astreait.com/services/">Salesforce</a></li>'),
document.write(""),
document.write('                            <li><a href="https://astreait.com/Agentic-AI/">Agentic-AI </a>'),
document.write(""),
document.write('                            <li><a href="#">Analytics </a>'),
document.write('                                <ul class="last_menu">'),
document.write('                                    <li><a href="https://astreait.com/Tableau_Analytics_Expertise/">Tableau CRM</a></li>'),
document.write('                                    <li><a href="https://astreait.com/CRM_Analytics_Salesforce_Integration/">CRM Analytics</a></li>'),
document.write('                                    <li><a href="https://astreait.com/Klipfolio/">Klipfolio</a></li>'),
document.write("                                </ul>"),
document.write("                            </li>"),
document.write('                            <li><a href="https://astreait.com/IntegrationsExpertise/">Integration</a></li>'),
document.write("                            </li>"),
document.write('                            <li><a href="https://astreait.com/Airtable-Expertise/">Airtable</a></li>'),
document.write('                            <li><a href="https://astreait.com/online-training/">Training </a></li>'),
document.write("                        </ul>"),
document.write(""),
document.write("                        \x3c!-- particular div started here  --\x3e"),
document.write(""),
document.write('                        <ol class="particular_services_toggle_show">'),
document.write('                            <li><a href="https://astreait.com/services/">Salesforce</a></li>'),
document.write('                            <li><a href="https://astreait.com/Agentic-AI/">Agentic-AI</a></li>'),
document.write(""),
document.write("                            <li>"),
document.write('                                <a class="particular_toggle1" href="#">Analytics </a>'),
document.write('                                <a class="particular_toggle2  col-11" href="#">Analytics</a>'),
document.write('                                <a class="col-1" href="javascript:void()"> <img class="services_toggleBI" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write('                                <ol class="particular_services_toggle_showBI">'),
document.write('                                    <li><a href="https://astreait.com/Tableau_Analytics_Expertise/">Tableau CRM</a></li>'),
document.write('                                    <li><a href="https://astreait.com/CRM_Analytics_Salesforce_Integration/">CRM Analytics</a></li>'),
document.write("                                </ol>"),
document.write("                            </li>"),
document.write('                            <li><a href="https://astreait.com/IntegrationsExpertise/">Integration</a></li>'),
document.write("                            </li>"),
document.write('                            <li><a href="https://astreait.com/Airtable-Expertise/">Airtable</a></li>'),
document.write('                            <li><a href="https://astreait.com/online-training/">Training </a></li>'),
document.write("                        </ol>"),
document.write("                        \x3c!-- particular div ended here  --\x3e"),
document.write(""),
document.write("                    </li>"),
document.write("                    \x3c!-- has sub child  started --\x3e"),
document.write(""),
document.write('                    <li class="has_particular"><a class="particular_toggle1" href="#">Clients </a>'),
document.write('                        <a class="particular_toggle2  col-11" href="#">Clients</a>'),
document.write('                        <a class="col-1" href="javascript:void()"> <img class="services_toggleClient" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write('                        <ul class="submenus">'),
document.write('                            <li class="subfirst"><a href="clients.html">Our Clients</a></li>'),
document.write('                            <li class="sublast"><a href="https://astreait.com/testimonials/">Clients Testimonials</a></li>'),
document.write("                        </ul>"),
document.write(""),
document.write('                        <ol class="particular_services_toggle_showClient">'),
document.write('                            <li class="subfirst"><a href="https://astreait.com/clients/">Our Clients</a></li>'),
document.write('                            <li class="sublast"><a href="https://astreait.com/testimonials/">Clients Testimonials</a></li>'),
document.write("                        </ol>"),
document.write("                    </li>"),
document.write(""),
document.write("                    \x3c!-- has sub child  started --\x3e"),
document.write('                    <li class="has_particular"><a class="particular_toggle1" href="#">Products</a>'),
document.write('                        <a class="particular_toggle2  col-11" href="#">Products</a>'),
document.write('                        <a class="col-1" href="javascript:void()"> <img class="services_togglePRDCT" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write(""),
document.write('                        <ul class="submenus">'),
document.write('                            <li> <a href="#">AppExchange Apps</a>'),
document.write('                                <ul class="last_menu">'),
document.write('                                    <li class="subfirst"><a href="https://astreait.com/PaidApps/">Paid Apps</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/FreeApps/">Free Apps</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/Flow-Templates/">Flow Templates</a></li>'),
document.write("                                </ul>"),
document.write("                            </li>"),
document.write(""),
document.write('                            <li><a href="https://astreait.com/AppExchangeComponents/">AppExchange Components</a></li>'),
document.write('                            <li><a href="https://astreait.com/QuipApps/">Quip Apps</a></li>'),
document.write('                            <li><a href="https://astreait.com/ChromeExtensions/">Chrome Extensions</a></li>'),
document.write('                            <li> <a href="#">Partner Products</a>'),
document.write('                                <ul class="last_menu">'),
document.write('                                    <li class="subfirst"><a href="https://astreait.com/VendorRelationshipManagement/">Vendor Relationship Management</a></li>'),
document.write('                                    <li><a href="https://astreait.com/Busivents/">Busivents</a></li>'),
document.write('                                    <li><a href="https://astreait.com/ActivityAttachmentNotifier/">Activity Attachment Notifier</a></li>'),
document.write('                                    <li><a href="https://astreait.com/AdminTestRunner/">Admin Test Runner</a></li>'),
document.write('                                    <li><a href="https://astreait.com/RecruitingPlatform_as_aService/">Recruiting Platform as a Service</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/XIRR/">XIRR</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/Rings_True/">RingsTrue</a></li>'),
document.write("                                </ul>"),
document.write("                            </li>"),
document.write("                        </ul>"),
document.write(""),
document.write("                        \x3c!-- particular div started here  --\x3e"),
document.write(""),
document.write('                        <ol class="particular_services_toggle_showPRDCT">'),
document.write(""),
document.write('                            <li class="has_particular"> <a href="#">AppExchange Apps</a>'),
document.write('                                <a class="particular_toggle2  col-11" href="#">AppExchange Apps</a>'),
document.write('                                <a class="col-1" href="javascript:void()"> <img class="services_toggleAppExchange" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write(""),
document.write('                                <ol class="particular_services_toggle_showAppExchange">'),
document.write('                                    <li class="subfirst"><a href="https://astreait.com/PaidApps/">Paid Apps</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/FreeApps/">Free Apps</a></li>'),
document.write("                                </ol>"),
document.write("                            </li>"),
document.write(""),
document.write('                            <li><a href="https://astreait.com/AppExchangeComponents/">AppExchange Components</a></li>'),
document.write('                            <li><a href="https://astreait.com/QuipApps/">Quip Apps</a></li>'),
document.write('                            <li><a href="https://astreait.com/ChromeExtensions/">Chrome Extensions</a></li>'),
document.write(""),
document.write('                            <li class="has_particular"> <a href="#">Partner Products</a>'),
document.write('                                <a class="particular_toggle2  col-11" href="#">Partner Products</a>'),
document.write('                                <a class="col-1" href="javascript:void()"> <img class="services_togglePARTNERP" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write(""),
document.write('                                <ol class="particular_services_toggle_showPARTNERP">'),
document.write('                                    <li class="subfirst"><a href="https://astreait.com/VendorRelationshipManagement/">Vendor Relationship Management</a></li>'),
document.write('                                    <li><a href="https://astreait.com/Busivents/">Busivents</a></li>'),
document.write('                                    <li><a href="https://astreait.com/ActivityAttachmentNotifier/">Activity Attachment Notifier</a></li>'),
document.write('                                    <li><a href="https://astreait.com/AdminTestRunner/">Admin Test Runner</a></li>'),
document.write('                                    <li><a href="https://astreait.com/RecruitingPlatform_as_aService/">Recruiting Platform as a Service</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/XIRR/">XIRR</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/Rings_True/">RingsTrue</a></li>'),
document.write("                                </ol>"),
document.write("                            </li>"),
document.write(""),
document.write("                        </ol>"),
document.write(""),
document.write("                        \x3c!-- particular div ended here  --\x3e"),
document.write(""),
document.write("                    </li>"),
document.write("                    \x3c!-- has sub child  started --\x3e"),
document.write(""),
document.write("                    \x3c!-- resources ended --\x3e"),
document.write('                    <li class="has_particular"><a class="particular_toggle1" href="#">Resources </a>'),
document.write('                        <a class="particular_toggle2  col-11" href="#">Resources</a>'),
document.write('                        <a class="col-1" href="javascript:void()"> <img class="services_toggleRESOURCES" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write('                        <ul class="submenus">'),
document.write('                            <li class="subfirst"><a href="https://astreait.com/blogs/">Blogs</a></li>'),
document.write('                            <li><a href="https://astreait.com/casestudies/">Case Studies</a></li>'),
document.write('                            <li class="sublast"><a href="https://astreait.com/tutorial/">Tutorials</a></li>'),
document.write("                        </ul>"),
document.write(""),
document.write('                        <ol class="particular_services_toggle_showRESOURCES">'),
document.write('                            <li class="subfirst"><a href="https://astreait.com/blogs/">Blogs</a></li>'),
document.write('                            <li><a href="https://astreait.com/casestudies/">Case Studies</a></li>'),
document.write('                            <li class="sublast"><a href="https://astreait.com/tutorial/">Tutorials</a></li>'),
document.write("                        </ol>"),
document.write("                    </li>"),
document.write(""),
document.write("                    \x3c!-- resources ended --\x3e"),
document.write(""),
document.write("                    \x3c!-- About started --\x3e"),
document.write('                    <li class="has_particular"><a class="particular_toggle1" href="https://astreait.com/about-us/">About Us</a>'),
document.write('                        <a class="particular_toggle2  col-11" href="https://astreait.com/about-us/">About Us</a>'),
document.write('                        <a class="col-1" href="javascript:void()"> <img class="services_toggleABOUT" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write('                        <ul class="submenus">'),
document.write('                            <li class="subfirst"><a href="https://astreait.com/news/">News </a></li>'),
document.write('                            <li><a href="https://astreait.com/LifeAtAstrea/">Life At Astrea </a></li>'),
document.write('                            <li><a href="https://astreait.com/contact-us/">Contact Us</a></li>'),
document.write('                            <li><a href="https://astreait.com/leadership-team/">Leadership Team</a></li>'),
document.write('                            <li class="sublast"><a href="https://astreait.com/AstreaPartners/">Our Partners</a>'),
document.write('                                <ul class="last_menu">'),
document.write('                                    <li class="subfirst"><a href="https://astreait.com/Conga-Composer-Partnership/">Conga</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/Apsona-Partnership/">Apsona</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/FormAssembly-Partnership/">FormAssembly</a></li>'),
document.write(' <li class="sublast"><a href="https://astreait.com/jotform/">Jotform</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/PandaDoc-For-Salesforce/">PandaDoc</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/airSlate/">airSlate</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/Formstack/">Formstack</a></li>'),
document.write('                                    <li class="sublast"><a href="https://astreait.com/StoreConnect/">StoreConnect</a></li>'),
document.write("                                </ul>"),
document.write("                            </li>"),
document.write("                        </ul>"),
document.write(""),
document.write('                        <ol class="particular_services_toggle_showABOUT">'),
document.write('                            <li class="subfirst"><a href="https://astreait.com/news/">News </a></li>'),
document.write('                            <li><a href="https://astreait.com/LifeAtAstrea/">Life At Astrea </a></li>'),
document.write('                            <li><a href="https://astreait.com/contact-us/">Contact Us</a></li>'),
document.write('                            <li><a href="https://astreait.com/leadership-team/">Leadership Team</a></li>'),
document.write('                            <li class="sublast"><a href="https://astreait.com/AstreaPartners/">Our Partners</a></li>'),
document.write("                        </ol>"),
document.write("                    </li>"),
document.write(""),
document.write("                    \x3c!-- About ended --\x3e"),
document.write(""),
document.write("                    \x3c!-- About started --\x3e"),
document.write('                    <li class="has_particular"><a class="particular_toggle1" href="careers.html">Career</a>'),
document.write('                        <a class="particular_toggle2  col-11" href="https://astreait.com/about-us/">About Us</a>'),
document.write('                        <a class="col-1" href="javascript:void()"> <img class="services_toggleABOUT" src="https://astreait.com/img/down-arrow.png"> </a>'),
document.write(""),
document.write('                        <ol class="particular_services_toggle_showABOUT">'),
document.write('                            <li class="subfirst"><a href="https://astreait.com/news/">News </a></li>'),
document.write('                            <li><a href="https://astreait.com/LifeAtAstrea/">Life At Astrea </a></li>'),
document.write('                            <li><a href="https://astreait.com/contact-us/">Contact Us</a></li>'),
document.write('                            <li><a href="https://astreait.com/leadership-team/">Leadership Team</a></li>'),
document.write('                            <li class="sublast"><a href="https://astreait.com/AstreaPartners/">Our Partners</a></li>'),
document.write("                        </ol>"),
document.write("                    </li>"),
document.write(""),
document.write("                    \x3c!-- About ended --\x3e"),
document.write(""),
document.write("                </ul>"),
document.write("            </nav>"),
document.write("        </div>"),
document.write(""),
document.write("    </header>");

